name: jupyterlab-drawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - doit ==0.32
  - flake8
  - isort <5
  - jupyterlab >=2.2.0,<3.0.0a0
  - nodejs >=12,<13.0.0a0
  - pyflakes
  - python >=3.8,<3.9.0a0
