name: ipydrawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - babel
  - black
  - bqplot
  - doit
  - flake8
  - httpx
  - ipywidgets
  - isort <5
  - json-e
  - jupyter-telemetry >=0.1.0 # ick, but fails pip check
  - jupyterlab >=3.0.0,<4.0.0a0
  - lxml
  - matplotlib-base
  - nbgitpuller
  - networkx
  - nodejs >=12,<13.0.0a0
  - pandas
  - pillow
  - pip
  - pyflakes
  - pygraphviz
  - pypdf2
  - pytest
  - python >=3.8,<3.9.0a0
  - requests_cache
  - shapely
  - tabulate
  - twine
  - wheel
  - pip:
      - graphviz2drawio
