on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: utf-8
  ATEST_RETRIES: 3
  CACHE_EPOCH: 0

jobs:
  ci:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos', 'windows']
        python-version: ['3.6', '3.9']
    steps:
      - name: configure line endings
        run: |
          git config --global core.autocrlf false

      - name: checkout
        uses: actions/checkout@v2

      - name: cache (conda)
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-conda-${{ matrix.python-version }}-

      - name: cache (yarn)
        uses: actions/cache@v1
        with:
          path: .yarn-packages
          key: |
            ${{ env.CACHE_EPOCH }}-yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.CACHE_EPOCH }}-yarn-${{ runner.os }}-
            ${{ env.CACHE_EPOCH }}-yarn-

      - name: install (conda)
        uses: conda-incubator/setup-miniconda@master
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: '*'
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: build (linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash -l {0}
        run: |
          doit all -n8 || doit all

      - name: build (macos)
        if: ${{ contains(matrix.os, 'macos') }}
        shell: bash -l {0}
        run: |
          doit all -2 || doit all

      - name: build (windows)
        if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd /C CALL {0}
        run: |
          doit all || doit all

      - name: clean (windows)
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          taskkill /F /IM python.exe || echo "no python"
          taskkill /F /IM node.exe || echo "no node"

      - name: report (robot)
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_number }} atest ${{ matrix.os }}${{ matrix.python-version }}
          path: ./atest/output
