on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHONUNBUFFERED: 1

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      SKIP_DRAWIO: 1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: .yarn-packages
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
            yarn-

      - uses: goanpeca/setup-miniconda@v1.6.0
        with:
          activate-environment: jupyterlab-drawio
          auto-activate-base: false
          environment-file: environment.yml
          show-channel-urls: true
          use-only-tar-bz2: true

      - if: ${{ !contains(matrix.os, 'windows') }}
        shell: bash -l {0}
        run: doit || doit

      - if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd /C CALL {0}
        run: call scripts\win_ci.bat
